services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - main-network

  python:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # volumes:
      # - type: bind
      #   source: ./src
      #   target: /app
    volumes:
      - ./src:/app
    depends_on:
      - db
    ports:
      - "8082:8082"
      - "9092:9092"
    networks:
      - main-network
      - ip6net
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    links:
      - db:mysql_db

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - main-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - main-network
          

volumes:
  mysql_data:

networks:
  main-network:
    driver: bridge
  ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 2001:0DB8::/112
